# Generated by Django 5.2 on 2025-05-12 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallRecord',
            fields=[
                ('CallId', models.AutoField(primary_key=True, serialize=False)),
                ('PhoneName', models.CharField(max_length=10)),
                ('Phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+8869\\d{8}$')])),
                ('PhoneTime', models.CharField(max_length=10)),
                ('IsScam', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('FamilyID', models.AutoField(primary_key=True, serialize=False)),
                ('Fcode', models.CharField(max_length=50)),
                ('FamilyName', models.CharField(max_length=10)),
                ('Created_Time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scam',
            fields=[
                ('ScamId', models.AutoField(primary_key=True, serialize=False)),
                ('Category', models.CharField(max_length=10)),
                ('Phone', models.ForeignKey(db_column='Phone', on_delete=django.db.models.deletion.CASCADE, to='mysite.callrecord')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('Borndate', models.DateField()),
                ('Phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+8869\\d{8}$')])),
                ('Password', models.CharField(max_length=20)),
                ('CaregiverID', models.IntegerField()),
                ('Relationship', models.CharField(max_length=5)),
                ('Created_time', models.DateTimeField(auto_now_add=True)),
                ('FamilyID', models.ForeignKey(db_column='FamilyID', on_delete=django.db.models.deletion.CASCADE, to='mysite.family')),
            ],
        ),
        migrations.CreateModel(
            name='Med',
            fields=[
                ('MedId', models.AutoField(primary_key=True, serialize=False)),
                ('Disease', models.CharField(max_length=10)),
                ('MedName', models.CharField(max_length=10)),
                ('MedNote', models.CharField(max_length=50)),
                ('MedTime', models.DateTimeField()),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
        migrations.CreateModel(
            name='Hos',
            fields=[
                ('HosId', models.AutoField(primary_key=True, serialize=False)),
                ('ClinicPlace', models.CharField(max_length=20)),
                ('ClinicDate', models.DateField()),
                ('Doctor', models.CharField(max_length=10)),
                ('Num', models.IntegerField()),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
        migrations.CreateModel(
            name='HealthCare',
            fields=[
                ('HealthID', models.AutoField(primary_key=True, serialize=False)),
                ('BloodP', models.CharField(max_length=10)),
                ('BloodS', models.CharField(max_length=10)),
                ('Pluse', models.CharField(max_length=5)),
                ('Numsteps', models.CharField(max_length=5)),
                ('Date', models.DateTimeField()),
                ('UserID', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='mysite.user')),
            ],
        ),
        migrations.AddField(
            model_name='callrecord',
            name='UserId',
            field=models.ForeignKey(db_column='UserId', on_delete=django.db.models.deletion.CASCADE, to='mysite.user'),
        ),
    ]
