# Generated by Django 5.2 on 2025-05-19 02:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='callrecord',
            options={'verbose_name': 'Call record', 'verbose_name_plural': 'Call record'},
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': 'Family', 'verbose_name_plural': 'Family'},
        ),
        migrations.AlterModelOptions(
            name='healthcare',
            options={'verbose_name': 'Health care', 'verbose_name_plural': 'Health care'},
        ),
        migrations.AlterModelOptions(
            name='hos',
            options={'verbose_name': 'Hos', 'verbose_name_plural': 'Hos'},
        ),
        migrations.AlterModelOptions(
            name='med',
            options={'verbose_name': 'Med', 'verbose_name_plural': 'Med'},
        ),
        migrations.AlterModelOptions(
            name='scam',
            options={'verbose_name': 'Scam', 'verbose_name_plural': 'Scam'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'User'},
        ),
        migrations.RemoveField(
            model_name='healthcare',
            name='BloodP',
        ),
        migrations.RemoveField(
            model_name='healthcare',
            name='BloodS',
        ),
        migrations.RemoveField(
            model_name='user',
            name='CaregiverID',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Relationship',
        ),
        migrations.AddField(
            model_name='healthcare',
            name='Diastolic',
            field=models.IntegerField(default=80, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(150)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthcare',
            name='Systolic',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(250)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='RelatedId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RelatedFamily', to='mysite.user'),
        ),
    ]
